environment: "real"

data_processing:
  api_key: "YOUR_REAL_OKX_API_KEY"
  api_secret: "YOUR_REAL_OKX_API_SECRET"
  passphrase: "YOUR_REAL_OKX_PASSPHRASE"
  base_url: "https://www.okx.com"
  ws_url: "wss://ws.okx.com:8443/ws/v5/public"
  symbol: "BTC-USDT-SWAP"
  db_path: "data_real.db"
